<?php
/*
* ProBot Version: 4.0
* Laravel Version: 10x
* Description: This source file "app/Models/_Transaction.php" was generated by ProBot AI.
* Date: 2/24/2025 12:05:24 PM
* Contact: towhid1@outlook.com
*/
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Transaction extends Model{

    protected $fillable = [
        'voucher_ref',
        'transaction_date',
        'account_id',
        'amount',
        'description',
        'transaction_against',
        'debit',
        'credit',
        'user_id',
    ];

    function account(){
        return $this->belongsTo(Account::class);
    }
}
?>
